{
    'name': 'MyFatoorah Payment Gateway',
    'version': '19.0.1.0.0',
    'category': 'Accounting/Payment Acquirers',
    'summary': 'Payment Provider: MyFatoorah',
    'description': 'MyFatoorah Payment Gateway',
    'license': 'LGPL-3',
    'depends': ['payment', 'account', 'account_payment'],
    'data': [
        'security/myfatoorah_security.xml',
        'views/payment_myfatoorah_templates.xml',
        'data/payment_method_data.xml',
        'data/payment_provider_data.xml',
        'views/account_move_views.xml',
        'views/payment_link_action_views.xml',
        'views/payment_link_wizard_views.xml',
        'views/payment_refund_wizard_views.xml',
        'views/payment_provider_views.xml',
        'views/payment_transaction_views.xml',
        'views/myfatoorah_payment_template.xml',
    ],
    'post_init_hook': 'post_init_hook',
    'uninstall_hook': 'uninstall_hook',
    'installable': True,
    'application': True,
    'auto_install': False,
}
